default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: Plan0ffice*12
  host: localhost

development:
  <<: *default
  database: blogsite_db

test:
  <<: *default
  database: blogsite_test

production:
  <<: *default
  database: blogsite_db
  username: postgres
  password: Jindalee1!
